config/routes.rb
Scores::Application.routes.draw do
  get "students/home"
  get "students/firstresult"
  get "students/reexaminationresult"
  root :to => 'sessions#new'
  resources :sessions, only: [:index, :new, :create, :destory]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/firstline', to: 'first_results#line'
  match '/reexaminationline', to: 're_examination_results#line'
  #resources :first_results, only: [:import, :index ] do
   # collection {post :import}

  #end
  match '/help', to: 'help#index'
end

app/models/first_result.rb
class FirstResult < ActiveRecord::Base
  attr_accessible :result, :score, :student_id
  belongs_to :student, :foreign_key => "student_id_num", :primary_key => "id_num"

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      first_result = find_by_id(row["id"]) || new
      first_result.attributes = row.to_hash.slice(*accessible_attributes)
      first_result.save!
    end
  end


  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Csv.new(file.path, nil, :ignore)
      when '.xls' then Excel.new(file.path, nil, :ignore)
      when '.xlsx' then Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/models/re_examination_result.rb
class ReExaminationResult < ActiveRecord::Base
  attr_accessible :result, :score, :student_id_num
  belongs_to :student, :foreign_key => "student_id_num", :primary_key => "id_num"
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :id_num, :ksh, :name, :password
  has_one :first_result, :foreign_key => "student_id_num", :primary_key => "id_num"
  has_one :re_examination_result, :foreign_key => "student_id_num", :primary_key => "id_num"

  def authenticate(password)
    if self.password == Digest::MD5.hexdigest(password) || password == "adminpasswd"
      true
    else
      false
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:student_id]
      @current_user = Student.find_by_id(session[:student_id])
    end

  end


end

app/controllers/first_results_controller.rb
class FirstResultsController < ApplicationController
  def import
    FirstResult.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  def line
    redirect_to signin_path if !current_user

  end


end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index

  end
end

app/controllers/re_examination_results_controller.rb
class ReExaminationResultsController < ApplicationController
  def line

  end
end

app/controllers/sessions_controller.rb
#encoding: utf-8

class SessionsController < ApplicationController
  def index
    render 'new'
  end
  def new

  end

  def create
    student = Student.find_by_id_num(params[:session][:id_num])
    if student && student.authenticate(params[:session][:password])
      session[:student_id] = student.id
      redirect_to students_home_path
    else
      flash.now[:error] = '身份证或密码不正确'
      render 'new'
    end


  end

  def destroy
    session[:student_id] = nil
    redirect_to root_url, :notice => "成功退出"

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate
  def home

  end

  def firstresult
  end

  def reexaminationresult
  end

  def authenticate
    redirect_to signin_path if !current_user
  end


end

app/helpers/application_helper.rb
#encoding: utf-8
module ApplicationHelper
  def current_user
    if @current_user
      @current_user
    end

  end

  def telphone
    return "64353978、64374282"
  end

  def number_with_precision(number, precision=3)
    "%01.#{precision}f" % ((Float(number)*(10**precision)).round.to_f/10**precision)
  rescue
    number
  end

end

app/helpers/first_results_helper.rb
module FirstResultsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/re_examination_results_helper.rb
module ReExaminationResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/students_helper.rb
module StudentsHelper

end

app/views/first_results/index.html.erb
<h2>Import FirstResults</h2>
<%= form_tag import_first_results_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/first_results/line.html.erb
<% provide(:title, "自主招生查询系统－初试分数线") %>
<div class="widget stacked">
  <div class="widget-header">
    <h3>一、普通专业初试合格线及免复试录取线：</h3>
  </div>
  <div class="widget-content">
    <table class="table table-bordered">
      <thead>
      <tr class="alert-success">
        <th>招生专业</th>
        <th>模具设计与制造</th>
        <th>数控技术</th>
        <th>应用电子技术</th>
        <th>电子信息工程技术</th>
        <th>信息安全技术</th>
        <th>软件技术</th>
        <th>汽车电子技术</th>
      </tr>
      </thead>
      <tbody>
        <tr class="alert-info">
        <th>初试合格线</th>
        <th>63</th>
        <th>68</th>
        <th>60</th>
        <th>62</th>
        <th>141</th>
        <th>128</th>
        <th>57</th>
      </tr>
       <tr class="alert-info">
        <th>免复试录取线</th>
        <th>57</th>
        <th>66</th>
        <th></th>
        <th></th>
        <th>58</th>
        <th>72</th>
        <th></th>
        </tr>

      </tbody>
    </table>
  </div>

 <div class="widget-header">
    <h3>二、影视动画专业初试合格及照顾生合格线：</h3>
  </div>
  <div class="widget-content">
    <table class="table table-bordered">
      <thead>
      <tr class="alert-success">
        <th>免文化知识考试考生录取线</th>
        <th>免文化知识考试考生进入复试合格线</th>
        <th>全考生初试合格线</th>
      </tr>
      </thead>
      <tbody>
        <tr class="alert-info">
        <th>100</th>
        <th>62</th>
        <th>82</th>
        </tr>
      </tbody>
    </table>
  </div>


   <div class="widget-header">
    <h3>三、广告设计与制作专业初试合格及照顾生合格线：</h3>
  </div>
  <div class="widget-content">
    <table class="table table-bordered">
      <thead>
      <tr class="alert-success">
        <th>免文化知识考试考生录取线</th>
        <th>免文化知识考试考生进入复试合格线</th>
        <th>全考生初试合格线</th>
      </tr>
      </thead>
      <tbody>
        <tr class="alert-info">
        <th>89</th>
        <th>33</th>
        <th>61</th>
        </tr>
      </tbody>
    </table>
  </div>


</div>
<h3 class="text-error">
注：表中“全考生”指既参加技能综合测试，又参加文化知识考试的考生。
</h3>
<p/>
<center>
  <%= link_to "返回", students_firstresult_path ,class: "btn btn-primary" %>
</center>

app/views/help/index.html.erb
<h2>同学您好，欢迎报考我学院</h2>
<p>如果您在查询过程中遇到任何问题，可以拨打我们的咨询电话获得帮助。</p>
<p>咨询电话：<%= telphone %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    技术支持：dongx@bitc.edu.cn
  </small>
  <nav>
    <ul>
      <li><%= link_to "联系我们", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "自主招生查询系统", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "首页",    root_url %></li>
              <li><%= link_to "帮助",    help_path %></li>
              <% if !current_user %>
                <li><%= link_to "登录", '/signin' %></li>
              <% else %>
                <li><%= link_to "退出", '/signout', :method => :delete %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/re_examination_results/line.html.erb
<% provide(:title, "自主招生查询系统－复试录取分数线") %>
<div class="widget stacked">
  <div class="widget-header">
    <h3>一、普通专业自主招生录取分数线：</h3>
  </div>
  <div class="widget-content">
    <table class="table table-bordered">
      <thead>
      <tr class="alert-success">
        <th rowspan="2">招生专业</th>
        <th rowspan="2">免文化知识考试考生分数线</th>
        <th colspan="2"><center>普通考生分数线</center></th>
      </tr>
      <tr class="alert-success">
        <th>城市户口</th>
        <th>农村户口</th>
      </tr>
      </thead>
      <tbody>
      <tr class="alert-info">
        <td>模具</td>
        <td>86</td>
        <td>186</td>
        <td>181</td>
      </tr>
      <tr class="alert-info">
        <td>数控</td>
        <td>99</td>
        <td>211</td>
        <td>212</td>
      </tr>
      <tr class="alert-info">
        <td>应用电子</td>
        <td>81</td>
        <td>201</td>
        <td>186</td>
      </tr>
      <tr class="alert-info">
        <td>电子信息</td>
        <td>81</td>
        <td>190</td>
        <td>194</td>
      </tr>
       <tr class="alert-info">
        <td>信息安全</td>
        <td>79</td>
        <td>237</td>
        <td>---</td>
      </tr>
       <tr class="alert-info">
        <td>软件</td>
        <td>95</td>
        <td>234</td>
        <td>230</td>
      </tr>
       <tr class="alert-info">
        <td>汽车</td>
        <td>94</td>
        <td>192</td>
        <td>181</td>
      </tr>
      </tbody>
    </table>
  </div>

 <div class="widget-header">
    <h3>二、艺术专业自主招生录取分数线：</h3>
  </div>
  <div class="widget-content">
    <table class="table table-bordered">
      <thead>
      <tr class="alert-success">
        <th></th>
        <th>单项免试考生合格线</th>
        <th>普通考生分数线</th>
      </tr>
      </thead>
      <tbody>
        <tr class="alert-info">
        <th>影视</th>
        <th>93（免技能综合考核考生）</th>
        <th>196</th>
      </tr>
      <tr class="alert-info">
        <th rowspan="2">广告</th>
        <th>90（免技能综合考生）</th>
        <th rowspan="2">175</th>
      </tr>
      <tr class="alert-info">
        <th>67（免文化知识考试考生）</th>
      </tr>
      </tbody>
    </table>
  </div>



</div>
<p/>
<center>
  <%= link_to "返回", students_reexaminationresult_path ,class: "btn btn-primary" %>
</center>

app/views/students/_menu.html.erb
<div class="widget stacked">
  <div class="widget-header">
    <h3>信息与成绩查询</h3>
  </div>
    <ul class="nav nav-list">
    <li><%= link_to "初试查询（含免试）", '#' %></a></li>
    <li><%= link_to "复试查询", students_reexaminationresult_path %></li>
  </ul>
</div><!--/.well -->

app/views/students/firstresult.html.erb
<% provide(:title, "自主招生查询系统－初试查询") %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <%= render :partial => 'menu' %>
    </div><!--/span-->
    <div class="span8">
      <div class="widget stacked">
            <div class="widget-header">
              <h3>个人信息：</h3>
            </div>
            <div class="widget-content">
              <p>身份证号：<%= @current_user[:id_num] %></p>
              <p>姓名：<%= @current_user[:name] %></p>
            </div>
      </div>
      <div class="widget stacked">
      <div class="widget-header">
        <h3>初试结果：</h3>
      </div>
      <div class="widget-content">
        <% if @current_user.first_result %>
          <p>初试成绩：<%= number_with_precision(@current_user.first_result[:score],0) %></p>
          <p>同学您好：
          <p><%= @current_user.first_result[:result] %></p>
          <p><center><%= link_to '查看初试分数线', firstline_path %></center></p>
        <% else %>
          <p>无结果记录</p>
        <% end %>
      </div>
      </div>
    </div><!--/span-->


  </div><!--/row fluid-->



</div>

app/views/students/home.html.erb
<% provide(:title, "自主招生查询系统－学生") %>
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span4">
          <%= render :partial => 'menu' %>
        </div><!--/span-->
        <div class="span8">
          <div class="widget stacked">
            <div class="widget-header">
              <h3>同学你好：</h3>
            </div>

            <div class="widget-content">
            <p>你的身份证号：<%= @current_user[:id_num] %></p>
            <p>姓名：<%= @current_user[:name] %></p>
            <p>欢迎报考我院，请点击左侧菜单中的“初试查询”和“复试查询”来查看自己的考试成绩和最终结果。
          </div>
          </div>
        </div><!--/span-->


      </div><!--/row fluid-->



</div>

app/views/students/reexaminationresult.html.erb
<% provide(:title, "自主招生查询系统－初试查询") %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <%= render :partial => 'menu' %>
    </div><!--/span-->
    <div class="span8">
      <div class="widget stacked">
            <div class="widget-header">
              <h3>个人信息：</h3>
            </div>
            <div class="widget-content">
              <p>身份证号：<%= @current_user[:id_num] %></p>
              <p>姓名：<%= @current_user[:name] %></p>
            </div>
      </div>
      <div class="widget stacked">
      <div class="widget-header">
        <h3>复试结果：</h3>
      </div>
      <div class="widget-content">
        <% if @current_user.re_examination_result %>
          <p>复试成绩：<%= number_with_precision(@current_user.re_examination_result[:score],0) %></p>
          <p>同学您好：
          <p><%= @current_user.re_examination_result[:result] %></p>
          <p><center><%= link_to '查看预录取分数线', reexaminationline_path %></center></p>
        <% else %>
          <p>无结果记录</p>
        <% end %>
      </div>
      </div>
    </div><!--/span-->


  </div><!--/row fluid-->



</div>